version: '3'
services:
  next-app:
    build:
      context: ./jvtheque-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  bdd:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_DB: jvtheque_db
      POSTGRES_USER: jvtheque_user
      POSTGRES_PASSWORD: jvtheque_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: