apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvtheque-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jvtheque-db
  template:
    metadata:
      labels:
        app: jvtheque-db
    spec:
      containers:
        - name: postgres
          image: postgres:17.5-alpine3.22
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: jvtheque-db-secret
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: jvtheque-db-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jvtheque-db-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: jvtheque-db-pvc 
